# Generated by Django 5.1.5 on 2025-02-05 10:53

import django.db.models.deletion
import django_authx.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_authx', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='token_ttl',
        ),
        migrations.AlterField(
            model_name='session',
            name='refresh_token',
            field=models.CharField(db_default=django_authx.utils.generate_token, db_index=True, max_length=64, unique=True, verbose_name='refresh token'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default=django_authx.utils.generate_token, max_length=64, primary_key=True, serialize=False, verbose_name='session key'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
