# Generated by Django 5.1.5 on 2025-02-05 23:13

import django_authx.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_authx', '0002_remove_session_token_ttl_alter_session_refresh_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='sessions_mo_client__f89a4c_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='authx_sessi_user_id_3d4f17_idx',
            old_name='sessions_mo_user_id_e41bcb_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='authx_sessi_user_id_27bc8d_idx',
            old_name='sessions_mo_user_id_39ff3e_idx',
        ),
        migrations.RemoveField(
            model_name='session',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_data',
        ),
        migrations.AddField(
            model_name='session',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='session',
            name='refresh_token',
            field=models.CharField(db_index=True, default=django_authx.utils.generate_token, max_length=64, unique=True, verbose_name='refresh token'),
        ),
        migrations.AlterField(
            model_name='session',
            name='remember_session',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, extends session lifetime', verbose_name='remember session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='throttle_rate',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Throttle rate'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user_agent', 'ip_address'], name='authx_sessi_user_ag_f28051_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['last_activity'], name='authx_sessi_last_ac_c76d3e_idx'),
        ),
        migrations.AlterModelTable(
            name='session',
            table='authx_sessions',
        ),
    ]
